package org.jaagruk.core.tools

import org.jaagruk.core.catalog.ArTargets
import org.jaagruk.core.catalog.ModuleCatalog
import org.jaagruk.core.catalog.Pictogram
import org.jaagruk.core.speech.VoiceCommand
import java.io.File

/**
 * Writes the catalog's resource contract to a text file.
 *
 * The Android module has to supply a string for every key the catalog references, in English, Hindi
 * and Santali, and a drawable for every pictogram. `MissingTranslation` and `ContentDescription` are
 * fatal lint checks precisely because a blank button in front of a worker who cannot read the fallback
 * is a safety failure, not a cosmetic one.
 *
 * Keeping the list generated rather than hand-maintained means a scenario author who adds an option
 * cannot forget to tell the translators. Run it with `./gradlew :core:dumpCatalogManifest`.
 *
 * Deliberately in test sources: it is build tooling, and shipping it in `:core` would put a file-writing
 * `main` inside a library that phones depend on.
 */
object CatalogManifest {

    @JvmStatic
    fun main(args: Array<String>) {
        require(args.isNotEmpty()) {
            "usage: CatalogManifest <output-file>"
        }
        val target = File(args[0])
        target.parentFile?.mkdirs()

        val stringKeys = ModuleCatalog.requiredStringKeys()
        val voiceKeys = VoiceCommand.entries.map { it.labelKey }.sorted()
        val pictograms = Pictogram.entries.map { it.name }.sorted()
        val referencedTargets = ModuleCatalog.referencedArTargets().sorted()

        val text = buildString {
            appendLine("# Jaagruk catalog resource manifest")
            appendLine("# Generated by :core:dumpCatalogManifest. Do not edit by hand.")
            appendLine("# catalog_version=${ModuleCatalog.CATALOG_VERSION}")
            appendLine()

            appendLine("[string_keys] count=${stringKeys.size}")
            stringKeys.forEach { appendLine(it) }
            appendLine()

            appendLine("[voice_command_keys] count=${voiceKeys.size}")
            voiceKeys.forEach { appendLine(it) }
            appendLine()

            appendLine("[pictograms] count=${pictograms.size}")
            pictograms.forEach { appendLine(it) }
            appendLine()

            appendLine("[referenced_ar_targets] count=${referencedTargets.size}")
            referencedTargets.forEach { appendLine(it) }
            appendLine()

            appendLine("[modules] count=${ModuleCatalog.all.size}")
            ModuleCatalog.all.forEach { module ->
                appendLine(
                    "${module.moduleCode}\t${module.moduleId}\t${module.titleKey}\t" +
                        "scenarios=${module.scenarios.size}\t" +
                        "fullyImplemented=${module in ModuleCatalog.fullyImplemented}",
                )
            }
        }

        target.writeText(text)
        println("wrote ${stringKeys.size} string keys and ${pictograms.size} pictograms to $target")
    }
}
