package org.jaagruk.core.tools

import org.jaagruk.core.TestFixtures
import org.jaagruk.core.cert.Attestation
import org.jaagruk.core.cert.AttestationCodec
import org.jaagruk.core.cert.OutcomeFlags
import org.jaagruk.core.cert.QrCodec
import org.jaagruk.core.crypto.Sha256
import org.jaagruk.core.util.Hex
import java.io.File

/**
 * Regenerates `core/src/test/resources/fixtures/attestation_vectors.json`.
 *
 *     gradlew :core:generateFixtures
 *
 * The generated file is the single source of truth shared by two independent implementations of
 * the canonical encoding: Kotlin (`AttestationCodec`) and Python
 * (`backend/app/core/canonical.py`). Both are asserted against it, so neither can drift without
 * turning a test red — and a drift on either side would mean every certificate in the field
 * silently stops verifying on the server.
 *
 * Regenerate only when the format is being changed deliberately, and bump
 * `Attestation.FORMAT_VERSION` at the same time.
 */
object FixtureGenerator {

    private class Vector(
        val name: String,
        val description: String,
        val workerId: String,
        val attestation: Attestation,
    )

    @JvmStatic
    fun main(args: Array<String>) {
        val outputPath = args.firstOrNull()
            ?: "core/src/test/resources/fixtures/attestation_vectors.json"
        val file = File(outputPath)
        file.parentFile?.mkdirs()
        file.writeText(render())
        println("[jaagruk] wrote ${file.absolutePath}")
    }

    /** The committed JSON document, as text. Kept deterministic so the diff is meaningful. */
    fun render(): String {
        val vectors = buildVectors()
        val builder = StringBuilder()

        builder.appendLine("{")
        builder.appendLine("  \"_comment\": [")
        builder.appendLine("    \"Generated by core :generateFixtures. Do not edit by hand.\",")
        builder.appendLine("    \"Shared contract between the Kotlin and Python canonical encoders.\",")
        builder.appendLine("    \"Test-only key material: never used by any real deployment.\"")
        builder.appendLine("  ],")
        builder.appendLine("  \"formatVersion\": ${Attestation.FORMAT_VERSION},")
        builder.appendLine("  \"magic\": \"${AttestationCodec.MAGIC}\",")
        builder.appendLine("  \"qrTextPrefix\": \"${QrCodec.TEXT_PREFIX}\",")
        builder.appendLine(
            "  \"sitePrivateKeyHex\": \"${Hex.encode(TestFixtures.SITE_PRIVATE_KEY)}\",",
        )
        builder.appendLine(
            "  \"sitePublicKeyHex\": \"${Hex.encode(TestFixtures.SITE_PUBLIC_KEY)}\",",
        )
        builder.appendLine("  \"vectors\": [")

        vectors.forEachIndexed { index, vector ->
            val signed = TestFixtures.sign(vector.attestation)
            val canonical = AttestationCodec.canonicalBytes(vector.attestation)
            val a = vector.attestation

            builder.appendLine("    {")
            builder.appendLine("      \"name\": \"${vector.name}\",")
            builder.appendLine("      \"description\": \"${vector.description}\",")
            builder.appendLine("      \"siteId\": \"${a.siteId}\",")
            builder.appendLine("      \"seq\": ${a.seq},")
            builder.appendLine("      \"workerId\": \"${vector.workerId}\",")
            builder.appendLine("      \"workerIdHashHex\": \"${Hex.encode(a.workerIdHash)}\",")
            builder.appendLine("      \"moduleCode\": ${a.moduleCode},")
            builder.appendLine("      \"scorePermille\": ${a.scorePermille},")
            builder.appendLine("      \"medianLatencyMs\": ${a.medianLatencyMs},")
            builder.appendLine("      \"outcomeFlags\": ${a.outcomeFlags.bits},")
            builder.appendLine("      \"issuedAtEpochMin\": ${a.issuedAtEpochMin},")
            builder.appendLine("      \"prevRecordHashHex\": \"${Hex.encode(a.prevRecordHash)}\",")
            builder.appendLine("      \"canonicalHex\": \"${Hex.encode(canonical)}\",")
            builder.appendLine("      \"signatureHex\": \"${Hex.encode(signed.signature)}\",")
            builder.appendLine("      \"recordHashHex\": \"${Hex.encode(signed.recordHash)}\",")
            builder.appendLine("      \"qrText\": \"${QrCodec.encode(signed)}\"")
            builder.append("    }")
            builder.appendLine(if (index == vectors.lastIndex) "" else ",")
        }

        builder.appendLine("  ]")
        builder.appendLine("}")
        return builder.toString()
    }

    private fun buildVectors(): List<Vector> {
        val genesisWorker = "JH-DHN-001-W00001"
        val genesis = Attestation(
            siteId = "JH-DHN-001",
            seq = 1L,
            workerIdHash = AttestationCodec.workerIdHash(genesisWorker),
            moduleCode = 1,
            scorePermille = 842,
            medianLatencyMs = 2_400L,
            outcomeFlags = OutcomeFlags.of(OutcomeFlags.PASSED, OutcomeFlags.SITE_SCANNED_AR),
            issuedAtEpochMin = 29_400_000L,
            prevRecordHash = Sha256.ZERO,
        )
        val genesisSigned = TestFixtures.sign(genesis)

        val secondWorker = "JH-DHN-001-W00002"
        val second = Attestation(
            siteId = "JH-DHN-001",
            seq = 2L,
            workerIdHash = AttestationCodec.workerIdHash(secondWorker),
            moduleCode = 2,
            scorePermille = 731,
            medianLatencyMs = 5_120L,
            outcomeFlags = OutcomeFlags.of(
                OutcomeFlags.PASSED,
                OutcomeFlags.HESITATION,
                OutcomeFlags.BUDDY_DRILL,
                OutcomeFlags.SITE_SCANNED_AR,
            ),
            issuedAtEpochMin = 29_400_017L,
            prevRecordHash = genesisSigned.recordHash,
        )
        val secondSigned = TestFixtures.sign(second)

        val thirdWorker = "JH-BOK-007-W00311"
        val third = Attestation(
            siteId = "JH-BOK-007",
            seq = 1L,
            workerIdHash = AttestationCodec.workerIdHash(thirdWorker),
            moduleCode = 5,
            scorePermille = 1_000,
            medianLatencyMs = 0L,
            outcomeFlags = OutcomeFlags.NONE,
            issuedAtEpochMin = 0L,
            prevRecordHash = Sha256.ZERO,
        )

        val fourthWorker = "JH-XYZ-999-W99999"
        val fourth = Attestation(
            siteId = "J".repeat(Attestation.MAX_SITE_ID_BYTES),
            seq = Attestation.MAX_SEQ,
            workerIdHash = AttestationCodec.workerIdHash(fourthWorker),
            moduleCode = 255,
            scorePermille = 1_000,
            medianLatencyMs = Attestation.MAX_U32,
            outcomeFlags = OutcomeFlags.fromBits(OutcomeFlags.ALL_MASK),
            issuedAtEpochMin = Attestation.MAX_U32,
            prevRecordHash = ByteArray(32) { 0xFF.toByte() },
        )

        val fifthWorker = "JH-DHN-001-W00003"
        val fifth = Attestation(
            siteId = "JH-DHN-001",
            seq = 3L,
            workerIdHash = AttestationCodec.workerIdHash(fifthWorker),
            moduleCode = 1,
            scorePermille = 715,
            medianLatencyMs = 3_333L,
            outcomeFlags = OutcomeFlags.of(
                OutcomeFlags.PASSED,
                OutcomeFlags.REFRESHER,
                OutcomeFlags.ASSISTED_MODE,
            ),
            issuedAtEpochMin = 29_402_880L,
            prevRecordHash = secondSigned.recordHash,
        )

        return listOf(
            Vector(
                "genesis",
                "First certificate at a site: zero predecessor hash, seq 1.",
                genesisWorker,
                genesis,
            ),
            Vector(
                "linked_buddy_hesitant",
                "Second record, links to genesis, buddy drill with a hesitation flag.",
                secondWorker,
                second,
            ),
            Vector(
                "min_field_values",
                "Lower bounds: zero latency, zero timestamp, no flags, perfect score.",
                thirdWorker,
                third,
            ),
            Vector(
                "max_field_values",
                "Upper bounds: longest site id, max seq, max u32 fields, every defined flag.",
                fourthWorker,
                fourth,
            ),
            Vector(
                "refresher_assisted",
                "Refresher pass taken in assisted (pictogram/voice) mode.",
                fifthWorker,
                fifth,
            ),
        )
    }
}
