<#
.SYNOPSIS
    Installs a minimal Android SDK into tools/_android_sdk so :android-app can be compiled
    without Android Studio.

.DESCRIPTION
    Downloads the command-line tools, then installs exactly the packages the build needs:
    platform-tools, platforms;android-35 and build-tools;35.0.0. Nothing else, because a full
    SDK install is several gigabytes and the build does not use any of it.

    Writes local.properties on success, which is what makes settings.gradle.kts include
    :android-app on the next Gradle invocation.

    Safe to re-run: every step is skipped if it has already completed.
#>

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$repoRoot = Split-Path -Parent $PSScriptRoot
$sdkRoot = Join-Path $repoRoot 'tools\_android_sdk'
$downloadDir = Join-Path $sdkRoot 'downloads'
$cmdlineParent = Join-Path $sdkRoot 'cmdline-tools'
$cmdlineLatest = Join-Path $cmdlineParent 'latest'

# Pinned so a re-run months later installs the same toolchain.
$cmdlineToolsUrl = 'https://dl.google.com/android/repository/commandlinetools-win-11076708_latest.zip'
$compileSdk = '35'
$buildTools = '35.0.0'

Write-Host "[jaagruk] Android SDK root: $sdkRoot"
New-Item -ItemType Directory -Force -Path $downloadDir | Out-Null

# --- command-line tools ----------------------------------------------------
if (-not (Test-Path (Join-Path $cmdlineLatest 'bin\sdkmanager.bat'))) {
    $zipPath = Join-Path $downloadDir 'cmdline-tools.zip'
    if (-not (Test-Path $zipPath)) {
        Write-Host '[jaagruk] downloading command-line tools (~150 MB)'
        Invoke-WebRequest -Uri $cmdlineToolsUrl -OutFile $zipPath -TimeoutSec 900
    }

    Write-Host '[jaagruk] extracting command-line tools'
    $extractTo = Join-Path $downloadDir 'extracted'
    if (Test-Path $extractTo) { Remove-Item -Recurse -Force $extractTo }
    Expand-Archive -Path $zipPath -DestinationPath $extractTo -Force

    # The archive unpacks to cmdline-tools/, but sdkmanager insists on living at
    # cmdline-tools/latest/ or it cannot locate the SDK root.
    New-Item -ItemType Directory -Force -Path $cmdlineParent | Out-Null
    if (Test-Path $cmdlineLatest) { Remove-Item -Recurse -Force $cmdlineLatest }
    Move-Item -Path (Join-Path $extractTo 'cmdline-tools') -Destination $cmdlineLatest
} else {
    Write-Host '[jaagruk] command-line tools already present'
}

$sdkManager = Join-Path $cmdlineLatest 'bin\sdkmanager.bat'
if (-not (Test-Path $sdkManager)) {
    throw "sdkmanager.bat was not found at $sdkManager"
}

$env:ANDROID_HOME = $sdkRoot
$env:ANDROID_SDK_ROOT = $sdkRoot

# --- licences --------------------------------------------------------------
# Non-interactive: sdkmanager prompts per licence, so every prompt gets a 'y'.
Write-Host '[jaagruk] accepting SDK licences'
$licenceInput = ('y' * 1) + "`n"
$licenceAnswers = [string]::Join('', (1..40 | ForEach-Object { "y`n" }))
$licenceAnswers | & cmd /c "`"$sdkManager`" --sdk_root=`"$sdkRoot`" --licenses" 2>&1 |
    Select-Object -Last 3 | ForEach-Object { Write-Host "    $_" }

# --- packages --------------------------------------------------------------
$packages = @(
    'platform-tools',
    "platforms;android-$compileSdk",
    "build-tools;$buildTools"
)

foreach ($package in $packages) {
    Write-Host "[jaagruk] installing $package"
    $licenceAnswers | & cmd /c "`"$sdkManager`" --sdk_root=`"$sdkRoot`" `"$package`"" 2>&1 |
        Select-Object -Last 3 | ForEach-Object { Write-Host "    $_" }
}

# --- verify ----------------------------------------------------------------
$platformDir = Join-Path $sdkRoot "platforms\android-$compileSdk"
$buildToolsDir = Join-Path $sdkRoot "build-tools\$buildTools"

if (-not (Test-Path $platformDir)) { throw "platform android-$compileSdk was not installed" }
if (-not (Test-Path $buildToolsDir)) { throw "build-tools $buildTools were not installed" }

# --- local.properties ------------------------------------------------------
# settings.gradle.kts looks for sdk.dir here, so writing it is what switches :android-app on.
$localProperties = Join-Path $repoRoot 'local.properties'
# Java properties escaping: one backslash in front of a backslash, and one in front of a colon. In a
# PowerShell -replace the replacement string is not regex, so '\\' produces exactly two characters. The
# earlier '\\\\' produced four and yielded a path with doubled separators that Windows tolerated and every
# path-reading script did not.
$escaped = $sdkRoot -replace '\\', '\\' -replace ':', '\:'
@"
# Generated by tools/bootstrap-android-sdk.ps1. Machine specific; not committed.
sdk.dir=$escaped
"@ | Set-Content -Path $localProperties -Encoding ASCII

Write-Host ''
Write-Host '[jaagruk] Android SDK ready.'
Write-Host "          sdk.dir written to $localProperties"
Write-Host '          Build with:  .\gradlew.bat :android-app:assembleDebug'
